fancybox: true ## If you want to use fancybox please set the value to true

disqus: ## Your disqus_shortname, e.g. haomwei

google_search: true ## Use Google search, true/false

baidu_search: ## Use Baidu search, true/false

swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT

tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293

duoshuo: imciel

baidu_analytics: 7d99c6e5e5cfb8cdef57d7cbf7b1010a

google_analytics: UA-51259806-3

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: guestbook
    directory: guestbook/
    icon: icon-guestbook
  - page: about
    directory: about/
    icon: icon-about
  - page: rss
    directory: atom.xml
    icon: icon-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments

links:
  - title: site-name1
    url: http://www.example1.com/
  - title: site-name2
    url: http://www.example2.com/
  - title: site-name3
    url: http://www.example3.com/

# Static files
js: https://dn-cielpark.qbox.me/js
css: https://dn-cielpark.qbox.me/css

# Theme version
version: 0.0.0
